version: '2.0'

services:
  nginx2alpine:
    restart: always
    image: nginx:1.11.6-alpine
    ports:
      - 8070:80
      #- 80:80
      - 443:443
    volumes:
      - /usr/local/nginx.bak/conf.d:/etc/nginx/conf.d
      - /usr/local/nginx.bak/nginx.conf:/etc/nginx/nginx.conf
      - /usr/local/nginx.bak/log:/var/log/nginx
      - /usr/local/nginx.bak/html:/var/www
     # - /etc/letsencrypt:/etc/letsencrypt