#s file uses the version 2 docker-compose file: format, described here:
# https://docs.docker.com/compose/compose-file/#version-2
#
# It extends the default configuration from docker-compose.yml to run the
# zipkin-elasticsearch container instead of the zipkin-mysql container.

version: '2'

services:
  # Run Elasticsearch instead of MySQL
  storage:
    image: elasticsearch:latest
    container_name: elasticsearch
    # Uncomment to expose the storage port for testing
    ports:
       - 9200:9200
    environment:
      - http.host=192.168.1.232
      - http.port=9200
      - transport.host=127.0.0.1 
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - xpack.security.enabled=false

  # Switch storage type to Elasticsearch
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    environment:
      - STORAGE_TYPE=elasticsearch
      # Point the zipkin at the storage backend
      - ES_HOSTS=elasticsearch
      # Uncomment to see requests to and from elasticsearch
      # - ES_HTTP_LOGGING=BODY
    ports:
      - 9411:9411
    depends_on:
      - storage 

  dependencies:
    image: openzipkin/zipkin-dependencies:latest
    container_name: dependencies
    entrypoint: crond -f
    environment:
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=elasticsearch
    depends_on:
      - storage
