# ===================================================================
# spring
# ===================================================================
spring:
  profiles:
    active: dev
  freemarker:
    suffix: .ftl
    templateEncoding: UTF-8
    template-loader-path: classpath:/templates/
    content-type: text/html
    html:
      path: /Users/vin/DevDemo/boot-jeesite/

# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 192.168.1.21:22122
#    - 192.168.1.106:22122
